dask_geopandas/backends.py
Creating a dask GeoDataFrame/GeoSeries with `from_geopandas` / `from_pandas` can be very expensive, because right now the tokenization converts the geometries to an object numpy array and then pickles that (which converts to WKB element by element). Even with the vectorized `to_wkb` this can be very slow for larger data (like 5s for 10 million points, which is something that fits easily in memory).
So therefore, for now, use a random UUID.
Some discussion at https://gitter.im/dask/dev?at=5edad44022dd444224ffcc0b 
Docs: https://docs.dask.org/en/latest/custom-collections.html#implementing-deterministic-hashing
=> Register GeometryArray tokenization with cheap random uuid

README.rst
Fixing the example for now, closes #16
(cc @Guts)
=> DOC: fix example + add Parquet note

dask_geopandas/core.py, tests/test_spatial_partitioning.py
Working towards https://github.com/jsignell/dask-geopandas/issues/8
For now I added a `spatial_partitions` attribute, which holds a GeoSeries with length of `npartitions`. And I implemented the `cx` indexer to slice based on the coordinates, making use of the spatial partitioning.  
So that ensures you can do something like `ddf.cx[-180:-70, 0:-80]`, and it will based on this specified bounding box first select the appropriate partitions, and then further select the rows of those partitions. 
There are still lots of todo's / things I am uncertain about:
- We need to add some "repartition" method that shuffles based on given partition bounds or that first calculates optimal partition bounds (there is a version in the old repo: https://github.com/mrocklin/dask-geopandas/blob/8133969bf03d158f …
=> ENH: Implement basic spatial partitioning

dask_geopandas/backends.py
We now get numpy FutureWarning due to LineString within array.
```
FutureWarning: The input object of type 'LineString' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'LineString', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
```
Since `from_shapely` does not need an array and can work with a list, I am passing it directly. Broken tests are unrelated (were already broken).
=> REF: resolve numpy FutureWarning

dask_geopandas/core.py
Explode implementation was moved from GeoPandasBase in https://github.com/geopandas/geopandas/pull/1720. This should fix the implementation here.
=> BUG: fix explode moved from GeoPandasBase in geopandas

.github/workflows/release_to_pypi.yml
Adding GitHub action to manage release. Copied from geopandas repo.
It is triggered on a tag starting `v` (as `v0.1.0`) pushed to repo and will:
1. upload a release to PyPI
2. create GitHub release
Someone needs to add a `PYPI_API_TOKEN` to repository secrets. Since there's no release on PyPI it can be anyone. Can do it myself and then give @jorisvandenbossche and @jsignell PyPI access or one of you can do it instead (so I don't claim the ownership).
=> GHA: Add release GitHub action

.github/workflows/tests.yaml, .pre-commit-config.yaml, dask_geopandas/backends.py, dask_geopandas/core.py
Reformatting with a new version of black to make CI happy. I have also updated pre-commit to the correct black repo.
Also adding some adaptations to dask main (#48)
Closes #48
=> TST: fix CI (black, dask master)

dask_geopandas/core.py, notebooks/basic-intro.ipynb, tests/test_core.py
The behaviour should follow GeoPandas' behaviour, that is
- Raises ValueError if setting a different crs with `allow_override=False`
- Overwrites the crs if `allow_override=True`
- Overwrites the crs when using `crs.setter`
closes #3
=> Check for `crs` before allowing `set_crs`

continuous_integration/envs/37-latest.yaml, continuous_integration/envs/38-latest.yaml, setup.py
@martinfleis @jsignell I don't know to what extent we want to test against different dask version (except latest release + master) in the current alpha phase of the project, but https://github.com/geopandas/dask-geopandas/pull/50 is adding some custom code for versions older than 2021.06, which would be not covered in the current CI setup
=> CI: test against different dask versions + update minimum dask version

dask_geopandas/backends.py, setup.py
This PR adds some compatibility updates for the upcoming `dask=2021.06.0` release. xref https://github.com/dask/dask/pull/7743#issuecomment-853693448
=> Add compatibility for Dask 2021.06.0

dask_geopandas/core.py, notebooks/basic-intro.ipynb, tests/test_core.py
Creates a `copy()` method that copies `spatial_partitions`, as discussed in https://github.com/geopandas/dask-geopandas/issues/55
=> Copy `spatial_partitions` when copying `GeoDataFrame`

dask_geopandas/core.py, tests/test_core.py
- sets the crs on spatial_partitions
- propagates them to the resulting dataframe
closes #58
=> BUG: set_crs takes spatial_partitions into account

dask_geopandas/__init__.py, dask_geopandas/sjoin.py, tests/test_sjoin.py
Updated version of the original implementation at https://github.com/mrocklin/dask-geopandas/blob/8133969bf03d158f51faf85d020641e86c9a7e28/dask_geopandas/core.py#L409-L430 written by @mrocklin
Still needs to have tests and docs etc, but I thought this could be helpful for discussion to already put up a simple spatial join algorithm that can use spatial partitioning information if available (and if not combines every partition of the left with every partition of the right dataframe).
=> ENH: basic spatial join

dask_geopandas/core.py
While inspecting the task graphs, I noticed that some methods from dask_geopandas were not showing up properly. The reason is that we had for example a task graph key such as " from_pandas-539469e91d2728523cacb4ce24809e38-total_bounds-agg-5c149902dcdf5b43358d736407dca688" (from `token=self._name + "-total_bounds"`, where in this case the parent was created from a pandas dataframe) which gets abbreviated to "from_pandas" in the visualization and html repr. With this change, it would get abbreviated as "total_bounds-agg".
I looked in dask.dataframe itself, and they don't seem to prepend the token with `self._name`. For some methods they do prepend with `series-` or `dataframe-` (this is defined as `self._token_prefix`). We could also do something similar and add a "geo-" prefix. Although I …
=> Don't prepend task token with parent object name

.pre-commit-config.yaml
Pre-commit was complaining with
```
[WARNING] The 'rev' field of repo 'https://github.com/psf/black' appears to be a mutable
reference (moving tag / branch).  Mutable references are never updated after first install
and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository
for more details.  Hint: `pre-commit autoupdate` often fixes this.
```
=> DEV/CI: update black and flake8 versions (pre-commit autoupdate)

README.rst
Fixes two typos in README.rst
* Line 51: `set_geometry` : ``set_geometry``
* Line 62: dff: dff
=> DOC: Fix small typos in README.rst

dask_geopandas/core.py
The meta in `_Frame`  expects a geopandas object, not a cudf object.
=> DOC: Fix docstring meta for _Frame in core.py

dask_geopandas/__init__.py, dask_geopandas/clip.py, tests/test_clip.py
A couple of notes/questions
- Is the token correct like this? (not using `gdf._name`, starting with `clip`)
- I have imported a pytest fixture from `test_core` and had to ignore flake warnings because of it. Not sure this is best way to go about it.
Commit message:
```
If no spatial partitions are available, just map_partitions
If spatial partitions are available, construct the graph
only for spatial partitions intersecting the mask.
keep_geom_type is always false for clipping the 
spatial partitions: otherwise we'd be falsely creating
new partition(s)
```
closes #57
=> ENH: Implement geopandas.clip

dask_geopandas/core.py, tests/test_core.py
If we rely on the dask implementation instead of overriding it, we actually already get a repr with the correct class name included:
```python
In [1]: import dask_geopandas
In [2]: df = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))
In [3]: ddf = dask_geopandas.from_geopandas(df, npartitions=4)
In [4]: ddf
Out[4]: 
Dask GeoDataFrame Structure:
pop_est continent    name  iso_a3 gdp_md_est  geometry
npartitions=4                                                       
0               int64    object  object  object    float64  geometry
45                ...       ...     ...     ...        ...       ...
90                ...       ...     ...     ...        ...       ...
135               ...       ...     ...     ...        ...       ...
176               ... …
```
=> ENH: improve text repr of GeoSeries/GeoDataFrame

dask_geopandas/io/parquet.py, tests/io/test_parquet.py
This sets the CRS when reading back a file that was written with the `geo-arrow-spec`'s metadata.
It's moves the conversion of the Dask `meta` dataframe down to a private method unfortunately, but AFAICT, that's the most convenient place to get access to the Parquet Dataset, so that we can read the `.schema.metadata`. I didn't look too closely.
Closes https://github.com/geopandas/dask-geopandas/issues/96
=> BUG: read CRS in read_parquet

dask_geopandas/morton_distance.py
Cool project. While reading through some of the source code (and learning about some of the concepts) I noticed that the wikipedia page in the documentation was for a graphics concept and not the mathematics one. Perhaps the wiki page originally routed to a disambiguation page when the doc-string was first created.
=> Documentation: Update Z-order wikipedia link page reference

dask_geopandas/io/parquet.py, tests/io/test_parquet.py
Encountered this while trying the sjoin benchmarks from spatialpandas, getting warnings about mismatching CRS in sjoin.
=> BUG: correctly set CRS of spatial_partitions in read_parquet

continuous_integration/envs/37-latest.yaml, continuous_integration/envs/38-latest.yaml, continuous_integration/envs/39-dev.yaml, continuous_integration/envs/39-latest.yaml
In the meantime there are pyproj 3.1+ releases that have fixed the issue in pyproj 3.0 (https://github.com/geopandas/dask-geopandas/pull/36#issuecomment-791898795), so we can remove the global 2.6 pin. I noted in https://github.com/geopandas/dask-geopandas/pull/123 however that this seems to give a windows failure related to S3 / AWS (I suppose triggered by the packages updates, by no longer pinning to an old pyproj version and thus also old versions of other packages).
=> CI: remove the pyproj 2.6 pin

README.rst, dask_geopandas/core.py, requirements-dev.txt, tests/test_core.py
This enables the usage [in the readme](https://github.com/geopandas/dask-geopandas/blob/master/README.rst#example) to have a CRS on the resultant data frame (which is needed for writing to parquet).
Sidecar fixes:
- Swaps 'longitude' and 'latitude' in the readme as they were incorrect
- Adds a `requirements-dev.txt` file that contains the packages needed to run the test suite locally
=> Pass through `crs` when using `points_from_xy`

README.rst
If pyarrow is not installed, the following error occurs when writing Parquet tables (following the readme example):
```
>       meta, schema, i_offset = engine.initialize_write(
df,
fs,
path,
append=append,
ignore_divisions=ignore_divisions,
partition_on=partition_on,
division_info=division_info,
index_cols=index_cols,
schema=schema,
**kwargs_pass,
)
E       AttributeError: type object 'GeoArrowEngine' has no attribute 'initialize_write'
```
This is due to `pyarrow` being an optional dependency [here](https://github.com/gadomski/dask-geopandas/blob/6ce7b8e0390aed3b6a7584ba0f6e42d65d0c98e8/dask_geopandas/io/parquet.py#L12-L16). The error message could probably be made better as well, but I wasn't quite the best way to report an error from the `to_parquet` method …
=> DOC: Add a note that pyarrow is required to write Parquet

continuous_integration/envs/37-latest.yaml, continuous_integration/envs/38-latest.yaml, continuous_integration/envs/39-dev.yaml, continuous_integration/envs/39-latest.yaml, dask_geopandas/backends.py, setup.py, tests/test_core.py
`LooseVersion` is deprecated, replacing it with the recommended `packaging` alternative  as we did in https://github.com/geopandas/geopandas/pull/2084/
=> MAINT: replace LooseVersion with packaging

.github/workflows/tests.yaml, continuous_integration/envs/37-latest.yaml
Use official `conda-incubator` action and mambaforge. The current setup is super slow, this should help it. It mirrors geopandas/geopandas settings.
=> CI: use mamba on CI

dask_geopandas/core.py, tests/test_core.py
Closes #59, closes #116
I initially started fixing this on the Dask side, trying to ensure that Dask preserves the subclass but realised that we would still need to do something on our side to ensure that a named geometry column is correctly assigned. Since Dask recreates a DataFrame from a dict, this is lost.
=> BUG: fix set_index issue with shuffle="disk"

tests/test_core.py
We know that this test will always be failing for this exact version of dask, assuming it gets fixed on the dask side in the next version (https://github.com/dask/dask/issues/8611). So then let's skip it to get current CI a bit easier to interpret.
=> TST: skip dissolve split_out tests for dask 2022.01.1

dask_geopandas/clip.py, dask_geopandas/core.py, dask_geopandas/sjoin.py, doc/requirements.txt, doc/source/docs/reference/geodataframe.rst, doc/source/docs/reference/geoseries.rst, setup.py, tests/test_clip.py, tests/test_core.py, tests/test_sjoin.py
Closes #127, xref #130
- add `clip` as a GeoDataFrame method
- support GeoSeries in `clip` and add it the method
- add `sjoin` as a GeoDataFrame method
- change `op` to `predicate` in `sjoin`
=> ENH: match geopandas sjoin and clip API

dask_geopandas/io/parquet.py, tests/io/test_parquet.py
Address the second (reading) part of https://github.com/geopandas/dask-geopandas/issues/137
=> BUG: fix read_parquet with empty partitions (all-NaN bbox)

dask_geopandas/clip.py, tests/test_clip.py
Closes #152 
I am not sure why we had `.to_frame("geometry")` in there but it is not needed. 
I have also changed one test to use real world data because that fixture returns LineStrings as partitions since all points are in line (I don't that that it is an issue by itself).
=> BUG: ensure clip returns partitions as GeoSeries

dask_geopandas/core.py, doc/source/docs/reference/geodataframe.rst, tests/test_core.py
=> ENH: implement rename_geometry

dask_geopandas/geohash.py, dask_geopandas/hilbert_distance.py, dask_geopandas/morton_distance.py, tests/test_geohash.py, tests/test_hilbert_distance.py, tests/test_morton_distance.py
Closes #146
Check for empty or missing geometry and raise `ValueError` instead of returning 0 in `hilbert_distance`, `morton_distance` and `geohash`.
=> ENH: raise for empty geoms in sorting methods

dask_geopandas/core.py, doc/source/docs/reference/geodataframe.rst, doc/source/docs/reference/geoseries.rst, tests/test_core.py
Adding another batch of methods to get closer to the feature parity with GeoPandas (#130).
=> ENH: add GeoSeries.z and to_wkt, to_wkb on GeoSeries and GeoDataFrame

continuous_integration/envs/37-latest.yaml, continuous_integration/envs/38-latest.yaml, dask_geopandas/__init__.py, setup.py
See https://github.com/geopandas/dask-geopandas/pull/163#issuecomment-1039452906
With the latest changes of https://github.com/geopandas/dask-geopandas/pull/91, we accidentally started to require dask 2021.5.0. So one option to deal with this is to simply bump the minimum required version (I directly bumped to 2021.06.0, because we already disallow 2021.05.1)
=> DEP: bump dask minimum required version to 2021.06.0

dask_geopandas/io/parquet.py
I noticed that we were actually subclassing the legacy engine from dask, and not the newer pyarrow.dataset based one. This doesn't change anything for the rest in our code (all tests pass), and this should also get rid of a bunch of deprecation warnings (from pyarrow, from using the legacy APIs)
It might not yet be available for older dask versions, in which case I can add a fallback to subclass the legacy engine in that case.
=> Parquet IO: use dask pyarrow.dataset based engine instead of the legacy engine

.github/workflows/tests.yaml, continuous_integration/envs/37-minimal.yaml, continuous_integration/envs/39-no-optional-deps.yaml, tests/io/test_parquet.py
Now we have both pyarrow and pyogrio as optional dependencies for IO, we should ensure we don't accidentally make them required dependencies by importing them unconditionally. Copying the testing approach from geopandas.
=> CI: add test env with no optional dependencies

dask_geopandas/core.py
The current docstring for `spatial_shuffle` incorrectly asserts that the the default level is 15.
This should be 16.
=> DOC: Update spatial_shuffle level using default level 16

dask_geopandas/io/file.py, dask_geopandas/tests/io/test_file.py
Fix #179 
This sets division when creating the dataframe and sets the resulting
index to RangeIndex for each partition using the appropriate offsets for
each parition.
=> Set divisions and index in read_file

dask_geopandas/core.py
Related to https://github.com/geopandas/dask-geopandas/issues/76. Doesn't yet implement it when `spatial_partitions is None`, but should at least give a better error message (about an attribute error about None not having total_bounds)
=> Raise proper error message in .cx indexer if no spatial_partitions are set

dask_geopandas/core.py, dask_geopandas/tests/test_core.py
While looking at the custom collection dask dunder methods (for https://github.com/geopandas/dask-geopandas/pull/191), I noticed that our custom `__dask_postpersist__` is a bit outdated (since https://github.com/dask/dask/pull/7276 it should have a `rename` keyword) and that it lacks any handling of spatial_partitions.
So this PR updates it with the upstream version + passes through `spatial_partitions`
=> BUG: persist spatial_partitions information in persist()

dask_geopandas/io/parquet.py, dask_geopandas/tests/io/test_parquet.py, doc/source/index.md, doc/source/parquet.md
Adds a new `gather_spatial_partitions` keyword to `read_parquet`
to disable opening each file to get its spatial bounds. The name was
chosen to mimic dask's `gather_statistics` keyword.
Also adds a small docs section (I didn't see an easy way to
insert a snippet in the docstring).
Closes https://github.com/geopandas/dask-geopandas/issues/194.
---
One note of hesitation: I think Dask mid-transition for handling how it reads metadata. I'm wondering whether we should just rely on the behavior of dask's `gather_statistics` keyword. IIUC, both it and this new `gather_spatial_partitions` control whether there's a *per-file* operation in `read_parquet`.
Maybe @jcrist or @rjzamora have a recommendation on whether adding a new keyword here is going against where Dask is headed.
=> Optionally skip spatial bounds in read_parquet

dask_geopandas/core.py, dask_geopandas/sjoin.py, dask_geopandas/tests/test_sjoin.py
* make sure 'core.py' does not skip self.spatial_partitions quality check by removing hidden function bypass
* add conversion to geoseries in `sjoin.py'
=> BUG: convert spatial partitions to geoseries in sjoin result

continuous_integration/envs/310-latest.yaml, continuous_integration/envs/39-no-optional-deps.yaml, dask_geopandas/core.py
On top of https://github.com/geopandas/dask-geopandas/pull/228 (will rebase this once the other is merged)
Starting with dask 2022.9.1, groupby started to use shuffle by default with `split_out>1`, see https://github.com/dask/dask/pull/9453
But doing that currently doesn't work (at least with the test case). It comes down to `_meta_nonempty` failing to be determined, an issue with renamed columns and then the GeoDataFrame constructor fails with that:
https://github.com/geopandas/dask-geopandas/blob/bd355404dad23c8a1a5876834f569d54d85fc626/dask_geopandas/backends.py#L60-L63
First, it raises "The CRS attribute of a GeoDataFrame without an active geometry column is not defined. Use GeoDataFrame.set_geometry to set the active geometry column.", and after removing `crs=x.crs`, it raises …
=> COMPAT: specify shuffle=False in dissolve

.pre-commit-config.yaml, dask_geopandas/io/arrow.py, dask_geopandas/io/parquet.py
closes #225 
Updates method signature of the following so that they are compatible with all versions of `dask`, including `dask>=2022.12.0`:
* `dask_geopandas.io.arrow.ArrowDatasetEngine._arrow_table_to_pandas`
* `dask_geopandas.io.arrow.GeoDatasetEngine._arrow_table_to_pandas`
* `dask_geopandas.io.parquet.GeoArrowEngine._create_dd_meta`
It's been a little while since I played around with this, but I had written previously that [these lines in dask](https://github.com/dask/dask/blob/f463fcf28ff6404cc04f478b73704e35664bb5f0/dask/dataframe/io/parquet/arrow.py#L1073-L1078) are problematic, as it calls `_arrow_table_to_pandas`, where it wasn't called prior to `dask==2022.12.0`.
At the time, I thought we may need an update to `GeoDatasetEngine._arrow_table_to_pandas` to handle this, but I feel …
=> BUG: fix `read_parquet` with `dask>=2022.12.0`

CHANGELOG.md, dask_geopandas/core.py, dask_geopandas/tests/test_core.py
Closes https://github.com/geopandas/dask-geopandas/issues/237
=> Ensure spatial_partitions are properly pickled

dask_geopandas/io/arrow.py, dask_geopandas/io/parquet.py
In https://github.com/dask/dask/pull/10076, `use_nullable_dtypes` will be removed from `_create_dd_meta` signature. Making a corresponding change here.
=> `use_nullable_dtypes` arg removed in `dask`

continuous_integration/envs/310-latest.yaml, continuous_integration/envs/38-minimal.yaml, continuous_integration/envs/39-no-optional-deps.yaml, dask_geopandas/core.py, dask_geopandas/tests/test_core.py, setup.py
pandas 2.0 changed a behavior w.r.t. groupby and non-numeric columns. This test doesn't need to drop the columns anymore. xref https://github.com/geopandas/geopandas/issues/1999
=> [compat]: Fixed test for pandas>2

requirements-dev.txt
Hi i cloned the repo and tried running the following to run the tests
```
pip install -e .
pip install -r requirements-dev.txt 
```
but when i was running the test i hit the following error
```
❯ pytest dask_geopandas/tests
ERROR collecting dask_geopandas/tests/test_geohash.py _______________________________________________________________________________
ImportError while importing test module '/Users/jtmiclat/personal/dask-geopandas/dask_geopandas/tests/test_geohash.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.9.16/lib/python3.9/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
dask_geopandas/tests/test_geohash.py:6: in <module>
from pygeohash import encode
E …
```
=> Add missing dependency in requirements-dev.txt

dask_geopandas/tests/conftest.py
Currently there are lots of failures like
```
AssertionError: Attributes of GeoDataFrame.iloc[:, 0] (column name="name_left") are different
Attribute "dtype" are different
[left]:  object
[right]: string[pyarrow]
```
We will have to update our tests (or the assert equal method) to deal with this dtypes difference, but for now disabling this option to get the tests green again.
=> TST: disable dask dataframe.convert-strings (pyarrow strings) for now

continuous_integration/envs/310-latest.yaml, continuous_integration/envs/311-dev.yaml, continuous_integration/envs/311-latest.yaml
We are seeing timeouts with the latest moto, similarly as in dask itself: https://github.com/dask/dask/issues/10869. Therefore pinning to <5 for now.
=> TST/CI: pin moto<5 to fix timeout

continuous_integration/envs/39-no-optional-deps.yaml, dask_geopandas/tests/test_geohash.py, dask_geopandas/tests/test_hilbert_distance.py, dask_geopandas/tests/test_morton_distance.py
Given those are optional test dependencies and only used in a few tests, I think it's nice to skip those when you don't have them installed locally.
=> TST: skip tests that need pygeohash/hilbertcurve/pymorton if not installed

.github/workflows/tests.yaml, CHANGELOG.md, ci/envs/310-no-optional-deps.yaml, ci/envs/311-latest.yaml, ci/envs/312-dev.yaml, ci/envs/312-latest.yaml, ci/envs/39-minimal.yaml, dask_geopandas/backends.py, dask_geopandas/io/parquet.py, dask_geopandas/tests/io/test_parquet.py, dask_geopandas/tests/test_core.py, pyproject.toml
Updating minimum required versions and CI:
- Python 3.8 -> 3.9
- GeoPandas 0.10 -> 0.12
- dask/distributed 2021.06 -> 2022.06
and in addition also bumped the minimum tested versions for numpy 1.20 -> 1.23 and pyproj 2.6 -> 3.0
=> CI/RLS: update minimum supported versions (Python 3.9, geopandas 0.12, dask 2022.06)

.pre-commit-config.yaml, dask_geopandas/backends.py, dask_geopandas/clip.py, dask_geopandas/core.py, dask_geopandas/expr.py, dask_geopandas/geohash.py, dask_geopandas/hilbert_distance.py, dask_geopandas/io/arrow.py, dask_geopandas/io/file.py, dask_geopandas/io/parquet.py, dask_geopandas/morton_distance.py, dask_geopandas/sjoin.py, dask_geopandas/tests/conftest.py, dask_geopandas/tests/io/conftest.py, dask_geopandas/tests/io/test_arrow.py, dask_geopandas/tests/io/test_file.py, dask_geopandas/tests/io/test_parquet.py, dask_geopandas/tests/test_clip.py, dask_geopandas/tests/test_core.py, dask_geopandas/tests/test_geohash.py, dask_geopandas/tests/test_hilbert_distance.py, dask_geopandas/tests/test_morton_distance.py, dask_geopandas/tests/test_sjoin.py, dask_geopandas/tests/test_spatial_partitioning.py, pyproject.toml, setup.cfg
Mostly just copied geopandas' setup (with its latest changes to expand the usage of ruff in https://github.com/geopandas/geopandas/pull/3291 and https://github.com/geopandas/geopandas/pull/3297), with some minor edits to adjust for dask-geopandas
The diff is mostly from sorting imports, and only few actual code changes.
=> MAINT: update linting setup (align with geopandas, use ruff, move config to pyproject.toml)

dask_geopandas/backends.py, dask_geopandas/tests/test_distributed.py
This registers our own implementation for pyarrow table <-> (Geo)DataFrame conversion through the dispatch mechanism. The distributed p2p shuffle algorithm uses that under the hood (it converts to pyarrow to send the data to other workers), and so with this change (and with the latest distributed release, as we require the fix from https://github.com/dask/distributed/pull/8667), a distributed `spatial_shuffle()` now works.
=> Register arrow import/export dispatch to make p2p shuffle work

dask_geopandas/core.py, dask_geopandas/expr.py
Small follow-up on https://github.com/geopandas/dask-geopandas/pull/293 fixing some whitespace issue in the docstrings
=> DOC: fix indentation in docstring of from_wkb/from_wkt

.github/workflows/tests.yaml, ci/envs/311-latest-no-expr.yaml, dask_geopandas/backends.py
From https://github.com/conda-forge/dask-geopandas-feedstock/pull/17. For the default of `QUERY_PLANNING_ON` of `None`, we were always setting it to True (for recent pandas), while upstream dask still sets it to False (with warning) if `dask-expr` is not installed. 
So updating our logic here to mimic what dask does, also still allowing to use dask-geopandas without dask-expr with recent dask (although dask will still give a noisy warning in that case about installing dask-expr)
=> Allow to use latest dask without dask-expr

pyproject.toml
See discussion in https://github.com/conda-forge/dask-geopandas-feedstock/pull/17. 
While in theory it is still possible to use recent dask without dask-expr, dask will raise warning about it (by default, you can still silence the warning as well by setting `"dataframe.query-planning"` config to False), it's probably easier for our users to automatically get it installed.
=> RLS - packaging: depend on dask[dataframe] to automatically get dask-expr

dask_geopandas/io/file.py, dask_geopandas/tests/io/test_arrow.py, dask_geopandas/tests/io/test_backend_integration.py, dask_geopandas/tests/io/test_file.py, dask_geopandas/tests/io/test_parquet.py
=> Fix non-empty meta when reading from shapefiles

dask_geopandas/sjoin.py, dask_geopandas/tests/test_sjoin.py
Closes https://github.com/geopandas/dask-geopandas/issues/303
This is a simple fix. I think we might want to explore what a proper dask-expr Expression for this looks like. I'll look into that later.
=> Handle dask-expr optimizations in sjoin

requirements-dev.txt
When setting up the project for development, tests fail with the current `requirements-dev.txt` due to the dask diagnostics suite missing.
This includes the required diagnostics libraries (`bokeh` and `distributed`) to ensure all tests pass after a default dev environment setup.
=> Include dask[diagnostics] in dev requirements

dask_geopandas/core.py, dask_geopandas/expr.py, dask_geopandas/tests/test_core.py
Simple re-inclusion of the `crs` argument when passing metadata for `GeoSeries` and `GeoDataFrame` from `points_from_xy`.
Added a small assertion to `test_points_from_xy_with_crs` to ensure the CRS is present on the dask object prior to compute. Addresses #315.
=> fix missing crs in metadata for points_from_xy

CHANGELOG.md, dask_geopandas/expr.py, dask_geopandas/tests/test_core.py, doc/source/docs/reference/geoseries.rst
fixes dev CI and downstream dev CI by following geopandas in removal of `geom_almost_equals`.
=> remove geom_almost_equals
