- README.rst
I copied some content from the README of https://github.com/mrocklin/dask-geopandas, updated it, and added an installation note (especially to have PyGEOS installed as well).
> Update README with status, example, installation note

- notebooks/basic-intro.ipynb
It doesn't show / explain much, yet, but to have at least some example code.
> Add basic example notebook

- tests/test_core.py
> TST: add test to ensure GeoSeries.apply works with latest geopandas

- dask_geopandas/io/parquet.py
- tests/io/test_parquet.py
> BUG: fix column selection pushdown with parquet reader

- dask_geopandas/core.py
- tests/test_core.py
> BUG: preserve index in points_from_xy

- dask_geopandas/core.py
- tests/test_core.py
This depends a bit on the exact output of Dask, but worse what can happen if dask changes is that we fall back to the original dask version as is now.
> Adapt html repr to recognize GeoDataFrame

- README.rst
Update of installation instructions after we transferred the repo (plus some minor typos).
> DOC: change installation link from jsignell to geopandas

- continuous_integration/envs/37-latest.yaml
- continuous_integration/envs/38-latest.yaml
- continuous_integration/envs/39-dev.yaml
- continuous_integration/envs/39-latest.yaml
See discussion in https://github.com/geopandas/dask-geopandas/pull/36
> CI: pin pyproj to 2.6

- setup.py
> Update urls in setup.py

- notebooks/basic-intro.ipynb
> DOC: fix typo in basic-intro.ipynb

- notebooks/basic-intro.ipynb
Hi all! 
I'm super excited about this project, I tried out the example notebook and found that it's missing a numpy import, so I added it. 
In case I'm not going about this properly, feel free to delete this PR and fix it in the proper way.
> FIX: Add numpy import to example notebook

- dask_geopandas/core.py
A potential solution to #74. I am just not sure what are the memory implications of `to_dask_array()`.
> FIX: set known shape on total_bounds result

- dask_geopandas/core.py
- setup.py
> REF: skip union in calculate_spatial_partitions

- dask_geopandas/backends.py
- dask_geopandas/core.py
- tests/test_core.py
> BUG: fix meta_nonempty for non-default geometry column names

- dask_geopandas/io/parquet.py
- tests/io/test_parquet.py
> BUG: fix read_parquet with a non-default geometry column name

- dask_geopandas/io/parquet.py
- tests/io/test_parquet.py
Can be done as follow-up on https://github.com/geopandas/dask-geopandas/pull/107
~TODO: This doesn't yet restore the correct CRS for a different column~ This is also done now
> BUG: fix read_parquet for multiple geometry columns

- dask_geopandas/core.py
- tests/test_core.py
> BUG: fix set_geometry with a dask_geopandas.GeoSeries

- dask_geopandas/io/parquet.py
This fixes the Parquet tests with the last dask release.
It was already said in https://github.com/geopandas/dask-geopandas/pull/97 that we unfortunately needed to dig into a private dask API, and so that has now changed. We should still see to bring it up with dask if this can be made "semi-public" (for developers), but this patch should already fix it (and it's not that much code to keep compatibility with both older and newest dask).
> Update Parquet implementation for compatibility with latest dask

- dask_geopandas/core.py
- tests/test_core.py
check if spatial partitions is none before copying to fix #120
> BUG: do not copy spatial partitions when None

- .github/workflows/tests.yaml
xref https://github.com/geopandas/community/issues/7
This is the only occurrence of "master" that I could find.
> DEV: rename master to main

- tests/test_core.py
This should fix a new failure coming from dask main in a dev env.
> TST: fix meta in geoseries apply test

- dask_geopandas/core.py
- tests/test_hilbert_distance.py
- tests/test_morton_distance.py
Addresses the first todo point of https://github.com/geopandas/dask-geopandas/issues/85
> ENH: allow to specify known total_bounds for Hilbert/Morton distance

- dask_geopandas/core.py
- doc/source/docs/reference/geoseries.rst
- tests/test_core.py
xref https://github.com/geopandas/dask-geopandas/issues/130
> Add covers and covered_by methods

- dask_geopandas/core.py
- tests/test_hilbert_distance.py
- tests/test_morton_distance.py
xref https://github.com/geopandas/dask-geopandas/issues/85
> ENH: use total_bounds of spatial_partitions if available for Hilbert/Morton distance

- dask_geopandas/core.py
- tests/test_core.py
Closes https://github.com/geopandas/dask-geopandas/issues/66
@martinfleis this would have catched the bug in clip.py from https://github.com/geopandas/dask-geopandas/pull/156
> Turn spatial_partitions into property + validate value in setter

- README.rst
Follow-up on https://github.com/geopandas/dask-geopandas/pull/166
And move them next to the title
> Add docs/conda/gitter badge to README

- dask_geopandas/io/parquet.py
- tests/io/test_parquet.py
> ENH: more informative error message for empty parquet dataset

- dask_geopandas/core.py
- doc/source/docs/reference/geodataframe.rst
- tests/test_core.py
> BUG: fix to_dask_dataframe

- dask_geopandas/io/arrow.py
- tests/io/test_parquet.py
Closes #167
This will also first need a change in dask (-> https://github.com/dask/dask/pull/8741)
> ENH: enable to_parquet with partition_on with attribute column

- README.rst
- doc/source/docs/reference/geodataframe.rst
- doc/source/docs/reference/io.rst
- doc/source/getting_started.md
- doc/source/guide.md
- doc/source/guide/basic-intro.ipynb
- doc/source/index.md
- doc/source/installation.md
An update of a landing page and minor edits of some other pages in the documentation. The link to a rendered version is among Checks below.
> DOC: landing page and minor touches

- dask_geopandas/tests/io/test_arrow.py
Closes #187 and avoids https://github.com/dask/dask/issues/8964 being triggered.
> TST: avoid dask issue with set_index

- dask_geopandas/tests/io/test_parquet.py
The latest dask version stopped writing the `_metadata` and `_common_metadata` files by default (https://github.com/dask/dask/issues/8901), so our test assuming those files were written was failing. 
I changed the test to check both options explicitly (so not depending on the exact default, so it's robust for different versions, and also tests both ways).
> TST: latest dask no longer writes _metadata files by default

- dask_geopandas/backends.py
- dask_geopandas/io/arrow.py
Closes https://github.com/geopandas/dask-geopandas/issues/198
> Compat with dask 2022.06.0: fix schema inference in to_parquet

- CHANGELOG.md
- doc/source/changelog.rst
- doc/source/index.md
Adding a changelog ahead of 0.2.0 release.
> DOC: add changelog

- doc/source/parquet.md
update :doc:`guide/spatial-partitioning` to [guide/spatial-partitioning](guide/spatial-partitioning.md)
> fix broken rel link

- CONTRIBUTING.md
* changes dask contribution guidelines to geopandas contribution guidelines
* see #183
> [DOC] change to geopandas contrib guide

- .github/workflows/release.yml
- .github/workflows/tests.yaml
- continuous_integration/envs/310-latest.yaml
- continuous_integration/envs/311-dev.yaml
- continuous_integration/envs/311-latest.yaml
- continuous_integration/envs/38-minimal.yaml
- continuous_integration/envs/39-no-optional-deps.yaml
Some long overdue updates, since we were not yet testing with python 3.10 and 3.11
> CI: update versions in testing

- .github/workflows/tests.yaml
- continuous_integration/envs/311-latest.yaml
- dask_geopandas/core.py
- doc/source/index.md
- doc/source/installation.md
- setup.py
> COMPAT: allow using dask-geopandas with shapely 2.0 without pygeos

- doc/source/conf.py
> Exclude spatial partitioning notebooks

- readthedocs.yml
RTD is not building. This should fix it.
> DOC: fix the RTD configuration file

- ci/envs/310-no-optional-deps.yaml
- pyproject.toml
> remove distributed as a required dependency
